export const ADD_MENTOR_SUCCESS="ADD_MENTOR_SUCCESS";
export const ADD_MENTOR_FAIL="ADD_MENTOR_FAIL";
export const MENTOR_PROFILE_RESET="MENTOR_PROFILE_RESET";

export const SHOW_MENTOR_SUCCESS="SHOW_MENTOR_SUCCESS";
export const SHOW_MENTOR_FAIL="SHOW_MENTOR_FAIL";

export const MENTOR_UPDATE_PROFILE_SUCCESS = 'MENTOR_UPDATE_PROFILE_SUCCESS';
export const MENTOR_UPDATE_PROFILE_FAIL = 'MENTOR_UPDATE_PROFILE_FAIL';
export const MENTOR_UPDATE_PROFILE_RESET = 'MENTOR_UPDATE_PROFILE_RESET';

export const MENTOR_DETAILS_SUCCESS="MENTOR_DETAILS_SUCCESS";
export const MENTOR_DETAILS_FAIL="MENTOR_DETAILS_FAIL";

export const REMOVE_MENTOR="REMOVE_MENTOR";